baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "Mufanc's Notes"
theme = [ "overlay", "PaperMod" ]


# Markdown 配置
[markup.goldmark]
renderer = { unsafe = true }

# https://gohugo.io/functions/highlight/#options
[markup.highlight]
lineNos = false
style = "monokai"  # https://xyproto.github.io/splash/docs/


# 顶部菜单
[[menu.main]]
identifier = "search"
name = "搜索"
url = "search"
weight = 10

[[menu.main]]
identifier = "posts"
name = "文章"
url = "posts"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "tags"
weight = 30

[[menu.main]]
identifier = "categories"
name = "分类"
url = "categories"
weight = 40


# 主页
[params.homeInfoParams]
Title = "Mufanc 的笔记站"
Content = "原博客的主题并不十分适合文本阅读，所以以后一些技术类的文章就会移到这里来啦"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Mufanc"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/Mufanc"


[params]
ShowCodeCopyButtons = true


# 搜索
[outputs]
home = [ "HTML", "RSS", "JSON" ]

